# Generated by Django 2.0.2 on 2018-04-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateprofile', '0003_auto_20180401_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expiry_date',
            field=models.DateField(blank=True),
        ),
    ]
